Models/Recipes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Recipe_Saver.Models
{
    public class RecipeList
    {
        [Key]
        public int RecipeListID { get; set; }
        public string RecipeName { get; set; }
        public string RecipeLink { get; set; }
        public bool BookOrLink { get; set; }
    }
    public class NewRecipe
    {
        public string RecipeName { get; set; }
        public string RecipeLink { get; set; }
        public string RecipeBook { get; set; }
        public int RecipePageNo { get; set; }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Recipe_Saver.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Recipe_Saver.Data;
using Recipe_Saver.Models;
using Sentry;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Recipe_Saver.Pages
{
	public class IndexModel : PageModel
	{
		private readonly ILogger<IndexModel> _logger;
		private readonly IRecipeData _recipeSaver;
		public IndexModel(ILogger<IndexModel> logger, IRecipeData recipeSaver)
		{
			_logger = logger;
			_recipeSaver = recipeSaver;
		}
		public List<RecipeList> Recipes { get; set; }
		public NewRecipe NewRecipe { get; set; }
		public async Task<ActionResult> OnGet()
		{
			try
			{
				Recipes = await _recipeSaver.GetRecipeList();
				return Page();
			}
			catch (Exception er)
			{
				SentrySdk.CaptureException(er);
				throw new Exception(er.ToString());
			}
		}
		public async Task<IActionResult> OnPost()
		{
			try
			{
				await _recipeSaver.AddRecipe(Request.Form["txtRecipeName"].ToString()
						, Request.Form["txtRecipeLink"].ToString()
						, Request.Form["txtRecipeBook"].ToString()
						, Request.Form["txtRecipePageNo"]);
				return RedirectToPage("./Index");
			}
			catch (Exception ex)
			{
				SentrySdk.CaptureException(ex);
				throw new Exception(ex.ToString());
			}
		}
		[HttpPost]
		public async Task<IActionResult> OnPostArchive(IFormCollection collection)
		{
				try
				{
						await _recipeSaver.ArchiveRecipe(Convert.ToInt32(Request.Form["RecipeListID"]));
		return RedirectToPage("./Index", new { @redirect = "archive" });
				}
				catch (Exception ex)
				{
						SentrySdk.CaptureException(ex);
						throw new Exception(ex.ToString());
				}
		}
	}
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Recipe_Saver.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
@section Scripts {
<script type="text/javascript">
    $(document).ready(function () {
        $('#recipeTable').dataTable({
            "aoColumns": [
                { "sType": "html" },
                { "sType": "html" },
                { "sType": "html" }
            ],
            "columnDefs": [
                { responsivePriority: 1, "targets": 0 },
                { responsivePriority: 3, "targets": 1 },
                { responsivePriority: 2, "targets": 2 }
            ],
            "pagingType": "numbers",
            "paging": false,
            responsive: true,
            "order": [0, 'desc'],
            "language": {
                "emptyTable": "No data available in table"
            },
            stateSave: true
        });
        const urlParams = new URLSearchParams(window.location.search);
        const redirectParam = urlParams.get('redirect');
        console.log(redirectParam)
        if (redirectParam == "archive") {
            $('.archivedAlert').modal();
            setTimeout(function () {
                $('.archivedAlert').modal('hide');
            }, 1000);
        }
        $(".btnArchive").on("click", function () {
            $(".archiveID").val(this.id)
            $(".archiveConfirm").modal();
        })
        $("#url").on("click", function () {
            if ($("#url").is(':checked')) {
                $(".RecipeLink").removeClass("d-none");
                $(".RecipeBook").addClass("d-none");
            }
        })
        $("#book").on("click", function () {
            if ($("#book").is(':checked')) {
                $(".RecipeLink").addClass("d-none");
                $(".RecipeBook").removeClass("d-none");
            }
        })
    });
</script>
}
<div class="row pt-4">
    <div class="col-12">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
            Add
        </button>
        <table id="recipeTable" class="table table-striped table-borderless recipeTable">
            <thead class="thead-dark">
                <tr>
                    <th>Recipe</th>
                    <th>Location</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Recipes)
                {
                    <tr>
                        <td>
                            @item.RecipeName
                        </td>
                        <td>
                            @if (item.BookOrLink == false) {
                                <a href="@item.RecipeLink">@item.RecipeLink</a>
                            } else {
                                @item.RecipeLink
                            }
                        </td>
                        <td>
                            <button type="button" class="btn btn-danger btnArchive" id="@item.RecipeListID"><i
                                class="fas fa-archive"></i>
                                Archive</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Recipe</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post">
                <div class="modal-body">
                    <label>Name</label>
                    <input type="text" name="txtRecipeName" class="form-control" required />
                    <label>Where from</label><br />
                    @* <input type="text" name="txtRecipeLink" class="form-control" required /> *@
                    <input type="radio" id="book" name="recipeLocation" value="Book">
                    <label for="book">Book</label><br />
                    <input type="radio" id="url" name="recipeLocation" value="URL">
                    <label for="url">URL</label><br />
                    <div class="RecipeLink d-none">
                        <label>Link</label>
                        <input type="text" name="txtRecipeLink" id="txtRecipeLink" class="form-control" />
                    </div>
                    <div class="RecipeBook d-none">
                        <label>Book</label>
                        <input type="text" name="txtRecipeBook" id="txtRecipeBook" class="form-control" />
                        <label>Page No.</label>
                        <input type="number" name="txtRecipePageNo" id="txtRecipePageNo" class="form-control" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade archiveConfirm" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" asp-page-handler="Archive">
                <div class="modal-body">
                    Are you sure you want to archive that meal?
                    <input type="hidden" class="archiveID" name="RecipeListID" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Archive</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade archivedAlert" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="alert alert-success text-center" role="alert">
            Archived successful!
        </div>
    </div>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Recipe Saver</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" />
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.8/js/dataTables.responsive.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.8/css/responsive.dataTables.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="https://kit.fontawesome.com/8c04280d47.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <p class="navbar-brand">Recipe Saver</p>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Recipe Saver
        </div>
    </footer>

    @RenderSection("Scripts", required: false)
</body>
</html>